# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.version.version

'1.20.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
np.zeros(11).data

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
np.zeros(10)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [3]:
np.array(range(10,49))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.array(range(10,49))[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
x = np.array([[0,1,2], [3,4,5], [6,7,8]])
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [22]:
x = np.array([1,2,0,0,4,0])
np.where(x != 0)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
np.random.random((3,3,3))

array([[[0.87356484, 0.85221597, 0.4335625 ],
        [0.81822043, 0.2905471 , 0.81936276],
        [0.53705834, 0.00227806, 0.09541413]],

       [[0.45563356, 0.66782535, 0.92247083],
        [0.62931046, 0.43757947, 0.84753401],
        [0.2811515 , 0.7545592 , 0.88639918]],

       [[0.50142423, 0.768614  , 0.4981123 ],
        [0.24343955, 0.9120751 , 0.01762224],
        [0.67600044, 0.74314502, 0.24404708]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [31]:
x=np.random.random((10,10))
print("Valeur minimale de la matrice : ", x.min())
print("Valeur maximale de la matrice : ", x.max())

Valeur minimale de la matrice :  0.01108036221313946
Valeur maximale de la matrice :  0.9731523159178654


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
x = np.random.random(10)
print("Valeur moyenne de la matrice : ", x.mean())

Valeur moyenne de la matrice :  0.503390094245342


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [37]:
x = np.ones((3,3))
x[1:-1,1:-1]=0
x

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [42]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, constant_values=0)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [44]:
print("False")

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [51]:
np.diag(1+np.arange(4), k =-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
x=np.zeros((8,8))
x[1::2, ::2]=1
x[::2, 1::2]=1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [79]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [64]:
x = np.array([0,1])
np.tile(x,(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [70]:
x=np.random.random((5,5))
print(x)
x_min = x.min()
x_max = x.max()
x_normalize = (x - x_min/x_max-x_min)
print(x_normalize)

[[0.78451088 0.34089257 0.04377694 0.77367044 0.08320704]
 [0.05513321 0.07571347 0.00921029 0.36566635 0.32429819]
 [0.04872921 0.57471255 0.8069127  0.96986749 0.31675219]
 [0.85439618 0.75074642 0.9436621  0.45343669 0.50727505]
 [0.85035543 0.59957855 0.15148732 0.2322492  0.37763816]]
[[ 0.76580415  0.32218584  0.02507022  0.75496371  0.06450031]
 [ 0.03642648  0.05700674 -0.00949644  0.34695962  0.30559147]
 [ 0.03002248  0.55600582  0.78820597  0.95116076  0.29804546]
 [ 0.83568945  0.73203969  0.92495537  0.43472996  0.48856832]
 [ 0.8316487   0.58087182  0.13278059  0.21354247  0.35893143]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [80]:
color_rgba = np.dtype([('r', np.ubyte, 1),('g', np.ubyte, 1),('b', np.ubyte, 1),('a', np.ubyte, 1)])

C:\Users\loic8\AppData\Local\Temp/ipykernel_4720/4235926653.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color_rgba = np.dtype([('r', np.ubyte, 1),('g', np.ubyte, 1),('b', np.ubyte, 1),('a', np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [72]:
x = np.random.random((5,3))
y = np.random.random((3,2))
x.dot(y)

array([[0.51126714, 0.284837  ],
       [0.48765831, 0.50919343],
       [0.077525  , 0.11556363],
       [1.00615726, 0.52570305],
       [0.25572294, 0.22108023]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [94]:
x = np.arange(12)
x[(3<x) & (x<=8)]*=-1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [102]:
print(9)

9


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [126]:
'/'

'/'

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [106]:
print('nan')
print(0)
print('?')

nan
0
?


#### 29. How to round away from zero a float array ? (★☆☆)

In [114]:
x=np.random.uniform(-5, 5, 10)
np.ceil(np.abs(x))

array([3., 2., 4., 3., 2., 5., 1., 2., 4., 3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [115]:
x=np.random.randint(-10,10,10)
y=np.random.randint(-10,10,10)
np.intersect1d(x,y)

array([-9, -7, -4,  4,  7,  9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [127]:
'/'

'/'

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [117]:
True

True

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [125]:
today = np.datetime64('today','D')
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print('Yesterday : ', yesterday, " / Today : ", today, " / Tomorrow : ", tomorrow)

Yesterday :  2022-06-10  / Today :  2022-06-11  / Tomorrow :  2022-06-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [130]:
np.arange("2016-07", "2016-08", dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [136]:
x=np.random.uniform(0,10,10)
print(np.trunc(x))
print(np.floor(x))
print(x-x%1)
print(x.astype(int))

[6. 7. 8. 1. 6. 5. 6. 8. 4. 7.]
[6. 7. 8. 1. 6. 5. 6. 8. 4. 7.]
[6. 7. 8. 1. 6. 5. 6. 8. 4. 7.]
[6 7 8 1 6 5 6 8 4 7]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [140]:
x=np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [144]:
def generator():
    for x in range(10):
        yield x #yield = mot clé ~ return mais lié aux générateurs. diminue la complexité en "stagant" la boucle suivi de l'incrémentation

np.fromiter(generator(), dtype='int')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [147]:
x=np.random.random(10)
x.sort()
x

array([0.00532218, 0.175518  , 0.27125589, 0.38423279, 0.39175335,
       0.60381007, 0.66168534, 0.74402403, 0.77371827, 0.78143984])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [148]:
x=np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [149]:
a = np.random.randint(10)
b = np.random.randint(10)
if (a == b):
    print("Egal")
else :
    print("Non égal")

Non égal


#### 43. Make an array immutable (read-only) (★★☆)

In [150]:
x=np.random.random(10)
x.flags.writeable=False
x[2]

0.1665563779460697

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [156]:
x=np.random.random((10,2))
a,b = x[:,0], x[:,1]
lat = np.sqrt(a**2+b**2)
print(lat)
long = np.arctan2(b,a)
print(long)

[0.86112384 0.89976925 0.4696405  0.94176284 0.82293206 0.65919357
 0.78773059 0.78569755 0.73748782 1.12359785]
[1.36335742 0.63321077 0.7064231  0.29852499 0.48295339 0.15890497
 0.2593902  0.5181334  0.41260736 0.78563933]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [160]:
x=np.random.random(10)
x[x.argmax()]=0
x

array([0.31719222, 0.45594807, 0.73863095, 0.18497962, 0.51402122,
       0.        , 0.23796708, 0.80799068, 0.231834  , 0.07744389])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [162]:
x= np.random.random(10)
y= np.random.random(10)
c= 1.0 / (x.reshape((-1,1)) - y)
print(x)

[0.41704551 0.26563434 0.72540564 0.91231227 0.51191499 0.31787285
 0.34742189 0.46119919 0.62467321 0.89080751]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [168]:
for elem in [np.int0, np.int16, np.int32, np.int64, np.int8]:
    print(np.iinfo(elem).min)
    print(np.iinfo(elem).max)

for elem in [np.float32, np.float64]:
    print(np.finfo(elem).min)
    print(np.finfo(elem).max)

-9223372036854775808
9223372036854775807
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-128
127
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [175]:
np.set_printoptions()
x=np.zeros((32,32))
print(x)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)